# Generated by Django 4.1.4 on 2022-12-28 00:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaidLinkToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link_token", models.CharField(default="", max_length=100)),
                ("expiration", models.DateTimeField()),
                ("request_id", models.CharField(default="", max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="Article",
        ),
    ]
