# Generated by Django 4.1.4 on 2022-12-29 23:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "api",
            "0003_account_item_transaction_delete_plaidlinktoken_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="current_balace",
            new_name="current_balance",
        ),
    ]
