# Generated by Django 4.1.4 on 2023-01-29 02:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_transaction_detailed_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="investmentholding",
            name="holding_id",
        ),
    ]
