# Generated by Django 4.1.4 on 2023-01-29 03:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_alter_account_account_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investmentholding",
            name="security",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
