# Generated by Django 4.1.4 on 2023-03-30 16:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0019_institution_alter_item_institution_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="institution_id",
            new_name="institution",
        ),
    ]
