# Generated by Django 5.1.2 on 2024-12-24 22:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_rename_institution_id_item_institution"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="account",
            name="item_account_unique_constraint",
        ),
        migrations.RemoveConstraint(
            model_name="item",
            name="user_institution_unique_constraint",
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                fields=("item", "account_id"), name="item_account_unique_constraint"
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.UniqueConstraint(
                fields=("user", "institution"),
                name="user_institution_unique_constraint",
            ),
        ),
    ]
