# Generated by Django 5.1.2 on 2024-12-25 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_remove_account_item_account_unique_constraint_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="available_balance",
            field=models.FloatField(null=True),
        ),
    ]
