# Generated by Django 5.1.2 on 2024-12-25 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_alter_account_available_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investment",
            name="security_id",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="investment",
            name="security_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="investment",
            name="security_ticker",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
