# Generated by Django 4.1.4 on 2023-01-06 21:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("personalFinanceAppAPI", "0006_transactioncategory"),
    ]

    operations = [
        migrations.RenameField(
            model_name="investmentholding",
            old_name="security_id",
            new_name="security",
        ),
        migrations.RenameField(
            model_name="transactioncategory",
            old_name="transaction_id",
            new_name="transaction",
        ),
    ]
