# Generated by Django 4.1.4 on 2023-01-09 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalFinanceAppAPI', '0007_rename_security_id_investmentholding_security_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransactionCategory',
        ),
    ]
