# Generated by Django 4.1.4 on 2023-01-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personalFinanceAppAPI", "0008_delete_transactioncategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="detailed_category",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="transaction",
            name="primary_category",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
