# Generated by Django 4.1.4 on 2023-01-29 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("personalFinanceAppAPI", "0011_alter_investmentsecurity_ticker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="account_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="account",
            name="account_subtype",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="account",
            name="account_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="account",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="investmentholding",
            name="account",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="personalFinanceAppAPI.account",
            ),
        ),
        migrations.AlterField(
            model_name="investmentholding",
            name="security",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="personalFinanceAppAPI.investmentsecurity",
            ),
        ),
        migrations.AlterField(
            model_name="investmentsecurity",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="investmentsecurity",
            name="security_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="investmentsecurity",
            name="ticker",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="payment_channel",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="primary_category",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
