name: Secrets and Environment Variables Test

on:
  workflow_dispatch

jobs:
  top-secret:
    runs-on: ubuntu-latest
    environment: sandbox
    env:
      DJANGO_SECRET_VAR: ${{ vars.DJANGO_SECRET_VAR }}
      USER_NAME: ${{ vars.USER_NAME }}
    steps:
      - name: Read Django Environment Variable
        run: echo "My Django Secret Key is $DJANGO_SECRET_VAR"
      - name: Read User Name
        run: echo "My User Name is $USER_NAME"
      - name: Read Django Secret Key
        run: echo "My Django Secret Key is ${{ secrets.DJANGO_SECRET_KEY }}"
