name: Secreats and Environment Variables Test

on:
  workflow_dispatch

jobs:
  top-secret:
    runs-on: ubuntu-latest
    environment: sandbox
    env:
      DJANGO_SECRET_VAR: ${{ vars.DJANGO_SECRET_VAR }}
    steps:
      - name: Read Django Environment Variable
        run: echo "My Django Secret Key is ${{ vars.DJANGO_SECRET_VAR }}"
      - name: Read Django Secret Key
        run: echo "My Django Secret Key is ${{ secrets.DJANGO_SECRET_KEY }}"
